@startuml
title  AS-IS Component Diagram Template



actor "User" as Actor

package "Frontend Layer" {
    component [Frontend SPA] as SPA
    interface "<<HTTP>>" as bff_Interface
    component "Backend For Frontend" as BFF
}

package "IBM Integration Platform" {
    component "IBM API Connect" as APIConnect{
      component "API" as api
    }
    component "IBM App Connect" as AppConnect{
      component "Integration Server" as is{
        component "App" as service
      }
    }
    component "IBMMQ"{
      component "Queue_Manager"
    }
    
    component "IBMODM"{

      component "Rule Server" as RuleServer
    }
}

package "DMZ"{
  component "DataPower" as DataPower
}

package "Database" {
  component "QIWA"
  component "HRSD Replica" as Replica
  component "Payments"
}

package "HRSD"{
  component "QIWA Datapower" as HRSDDP
  component "HRSD Database" as HRSDDB
  component "HRSD Backend" as HRSD_Backend
  

}

package "GSN"{
  component "NIC" as NIC
  component "GOSI" as GOSI
  component "MOC" as MOC
  component "MOF" as MOF
  component "Other Agencies" as othersGSN
}

package "Internet"{
  component "Third parties" as tp
}

' Flow connections

Actor --> SPA : "<<HTTP>>"
SPA -->bff_Interface : <<HTTP>>
BFF -up- bff_Interface
BFF --> APIConnect : "<<HTTP>>"
APIConnect --> AppConnect : "<HTTP>>"
AppConnect -down-> IBMMQ : "<<AMQP>>"


AppConnect -down-> IBMODM : "<<HTTP>>"
AppConnect -down-> Database : "ODBC/JDBC"
AppConnect --down-> DataPower : "<<HTTP>>"
DataPower-down->HRSDDP : "<<HTTP>>"
HRSDDP-->HRSD_Backend : "<<HTTP>>"
HRSDDP-->HRSDDB : "<<ODBC>"
HRSDDP-down-->GSN :"<<HTTP>>"
HRSDDB-up- DataPower : "<<ODBC>>"
DataPower-up-Replica : "<<ODBC>>"
DataPower--down-->tp : "<<HTTP>>"
@enduml